### ISSUE TITLE
[E0716]: Temporary value dropped while borrowed

### ISSUE THREAD

**Issue by akka47** [netthier/rustris#2]
Hey there, I tried compiling according to the README instructions and I got the following errors:

```
   Compiling tinybmp v0.2.3
   Compiling rustris-efi v0.1.0 (/home/masijo/rustris)
error[E0716]: temporary value dropped while borrowed
  --> src/framebuffer.rs:51:13
   |
51 |             system_table()
   |             ^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
...
57 |         };
   |          - temporary value is freed at the end of this statement
58 | 
59 |         let gop = unsafe { &mut *protocol.get() };
   |                                  -------- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

error[E0716]: temporary value dropped while borrowed
   --> src/game.rs:140:13
    |
140 |             system_table()
    |             ^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
...
146 |         };
    |          - temporary value is freed at the end of this statement
147 | 
148 |         let keyboard = unsafe { &mut *protocol.get() };
    |                                       -------- borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value

error: aborting due to 2 previous errors
```
Best of luck!

**Comment by netthier** [comment]
I can't reproduce this issue for some reason. I've pushed a commit which updates both uefi and uefi_services to their latest versions, could you try compiling again with those?
Should that still not work, could you please send me the output of `rustc --version`?
The pointer returned by `system_table()` is valid until the program exits boot services, which in this case, it never does. (https://docs.rs/uefi-services/0.8.0/uefi_services/fn.system_table.html)

**Comment by akka47** [comment]
I'm terribly sorry, I was using an outdated version of rust. (FYI it was `rustc 1.51.0-nightly (a4cbb44ae 2021-01-20)`). This was my mistake. Closing the issue now.

**Comment by netthier** [comment]
Haha, no problem. I've added some lines to the build instructions which should be enough to ensure that the user has the latest nightly compiler!
